### ISSUE TITLE
Failed to load resource: the server responded with a status of 404 (Not Found)

### ISSUE THREAD

**Issue by markgreenwood** [MugsyCarter/my_portfolio#19]
favicon.ico triggers this error:
Failed to load resource: the server responded with a status of 404 (Not Found)

**Comment by MugsyCarter** [comment]
Make an icon, place at the bottom of links.
  <link rel="shortcut icon" href="images/favicon.ico">

**Comment by MugsyCarter** [comment]
I generated a favicon and linked it.
